version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - RDS_URL=${RDS_URL}
      - RDS_ENDPOINT=${RDS_ENDPOINT}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - MANAGEMENT_SERVER_PORT=${MANAGEMENT_SERVER_PORT:-8081}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mindhealth-network

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=${DB_NAME:-mindhealth}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-mindhealth}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mindhealth-network

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  aws_secret_key:
    file: ./secrets/aws_secret_key.txt
networks:
  mindhealth-network:
    driver: bridge